---
include:
###################
####################
### LILY58 START ###
####################

  # peripheral_right
  - board: nice_nano_v2
    shield: lily58_right_peripheral
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_lily58_right_peripheral

  # peripheral_left
  - board: nice_nano_v2
    shield: lily58_left_peripheral
    cmake-args: -DCONFIG_ZMK_SLEEP=y -DCONFIG_ZMK_IDLE_TIMEOUT=60000
    artifact-name: nice_lily58_left_peripheral

# Xiao_Dongle_Prospector
  - board: seeeduino_xiao_ble
#    shield: lily58_dongle_xiao prospector_adapter
    shield: lily58_dongle_xiao #dongle_screen
    cmake-args: 
      #- -DCONFIG_ZMK_KEYBOARD_NAME=\"lily58Dongle_X\" 
      - -DCONFIG_ZMK_STUDIO=y
      - -DCONFIG_ZMK_STUDIO_LOCKING=n
      - -DCONFIG_ZMK_IDLE_TIMEOUT=60000
      #- -DCONFIG_LV_COLOR_DEPTH=16
      #- -DCONFIG_LV_COLOR_DEPTH_16=y
      #- -DCONFIG_LV_COLOR_DEPTH_1=n
      #- -DCONFIG_LV_COLOR_16_SWAP=n
    artifact-name: xiao_lily58_dongle_xiao
    snippet: studio-rpc-usb-uart

##################
### LILY58 END ###
##################

############################
### SETTINGS_RESET START ###
############################W

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao_settings_reset

##########################
### SETTINGS_RESET END ###
##########################
